name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        # コンテキスト: ワークフローの実行、変数、ランナーの環境、ジョブ、ステップに関する情報にアクセスする方法 を利用したジョブを作成
        # https://docs.github.com/ja/actions/learn-github-actions/contexts
        # コンテキストは JSON オブジェクトなので、 ログで整形出力するには、toJSON 関数が必要
        # https://docs.github.com/ja/actions/learn-github-actions/expressions#tojson
        run: echo "${{ toJson(github) }}"