name: Reuseable Deploy
# 文法: https://docs.github.com/ja/actions/using-workflows/reusing-workflows
# 他のworkflowから参照された時実行される
on: 
  workflow_call:
    inputs:
      # 他のジョブから受け取る入力引数を定義。key名(artifact-name)は任意
      artifact-name:
        description: The name of deployable artifact files
        required: true
        # 以下のように指定しても良い。arfifact-nameの値の指定は必須ではない + デフォルト値をdistにする
        # required: false
        # default: dist
        # 入力引数の型
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          # 文法: https://docs.github.com/ja/actions/learn-github-actions/contexts#inputs-context
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploying and uploading...."