name: Reuseable Deploy
# 文法: https://docs.github.com/ja/actions/using-workflows/reusing-workflows
# 他のworkflowから参照された時実行される
on: 
  workflow_call:
    inputs:
      # 他のジョブから受け取る入力引数を定義。key名(artifact-name)は任意
      artifact-name:
        description: The name of deployable artifact files
        required: true
        # 以下のように指定しても良い。arfifact-nameの値の指定は必須ではない + デフォルト値をdistにする
        # required: false
        # default: dist
        # 入力引数の型
        type: string
    outputs:
      result:
        description: The result of the deployment operation
        # このファイル内で定義したjobsレベルでoutputsの値を受け取る 
        # 参考: https://docs.github.com/ja/actions/using-workflows/reusing-workflows#using-outputs-from-a-reusable-workflow
        value: ${{ jobs.deploy.outputs.outcome }}
    # 以下のようにして 他のworkflowからsecretを受け取ることができる
    # secrets:
    #  some-secret:
    #    required: true
jobs:
  deploy:
    outputs:
      # stepレベルで出力を受け取る
      # https://github.com/Knt44kw/github-actions-practice/blob/section1to5/.github/workflows/artifact_job_output.yaml#L37-L41 と同じ
      outcome: ${{ steps.set-result.outputs.step-result }}}
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          # 文法: https://docs.github.com/ja/actions/learn-github-actions/contexts#inputs-context
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploying and uploading...."
      - name: Set result output
        # https://github.com/Knt44kw/github-actions-practice/blob/section1to5/.github/workflows/artifact_job_output.yaml#L55-L61 と同じ
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT