name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        env:
          # 環境変数としてissue名を指定することでスクリプトインジェクションの対策となる
          ISSUE_TITLE: "${{ github.event.issue.title }}"
        run: |
          if [[ "$ISSUE_TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi